### PR TITLE
Improve task efficiency

### PR DESCRIPTION
**Pull request by mkjois**
CC @DanySK 

Finally got around to developing this to address #3. There are 3 commits:
1. Minor maintenance from my development in IntelliJ
2. All functional improvements. The commit message itself describes them.
3. Bump plugin version

Tested by publishing locally and using it in a completely separate Gradle project. If there were unit tests in this repo I'd try to add to them, but I'm not familiar enough with Gradle plugin development to create them from scratch.

Let me know what you think!

### CODE REVIEW

**Comment by DanySK** [comment]
I only have a question: did you test that it works? I remember that requests made without explicitly setting the useragent were failing.
If your testing goes ok, I am ready to merge and release a new version!

**Comment by mkjois** [comment]
@DanySK Yes I tested by publishing locally and using it in a different project. Javadocs were rendered properly and other non-Javadoc tasks weren't affected. Feel free to conduct your own tests.

**Comment by DanySK** [comment]
Manually merged in develop.

**Comment by mkjois** [comment]
@DanySK Please let me know when this is released. Thanks!

**Pull request closed without merging**
